#!/bin/bash -x
set -e

cont=$1

lxc exec $cont -- apt update
lxc exec $cont -- apt install -y x11-apps mesa-utils alsa-utils
lxc exec $cont -- bash -c "echo 'export DISPLAY=:0' >> /home/ubuntu/.bashrc"

echo -e "uid $(id -u ${USER}) 1000\ngid $(id -g ${USER}) 1000" | lxc config set $cont raw.idmap -
lxc stop $cont
lxc config device add $cont X0 disk path=/tmp/.X11-unix/X0 source=/tmp/.X11-unix/X0
lxc config device add $cont Xauthority disk path=/home/ubuntu/.Xauthority source=/home/${USER}/.Xauthority
lxc config device add $cont mygpu gpu
lxc config device set $cont mygpu uid 1000
lxc config device set $cont mygpu gid 1000
lxc start $cont
