#! /bin/bash

LXC_NAME=$1
CONTAINERS_PATH="/home/hack4u/.local/share/lxc"
VG_NAME="lxc"
MAPPER_PATH="/dev/mapper"

# Remove container
lxc-destroy -n $LXC_NAME 
#Unmount LV
sudo umount -l $MAPPER_PATH/$VG_NAME-$LXC_NAME
# Remove LV
sudo lvremove -f $VG_NAME/$LXC_NAME
# Remove folder 
rm -r $CONTAINERS_PATH/$LXC_NAME

exit 0