#! /bin/bash

CONTAINERS_PATH="/home/hack4u/.local/share/lxc"
VG_NAME="lxc"
MAPPER_PATH="/dev/mapper"

# For each VM
for LXC_NAME in $(lxcls); do
	# Check if LV is mounted
	if ! mount | grep $MAPPER_PATH/$VG_NAME-$LXC_NAME > /dev/null; then
		echo "Mounting "$LXC_NAME
		sudo mount $MAPPER_PATH/$VG_NAME-$LXC_NAME $CONTAINERS_PATH/$LXC_NAME
	fi
done