#! /usr/bin/python3
import lxc, sys

HEADER = '\033[95m'
OKBLUE = '\033[94m'
OKGREEN = '\033[92m'
WARNING = '\033[93m'
FAIL = '\033[91m'
ENDC = '\033[0m'
BOLD = '\033[1m'
UNDERLINE = '\033[4m'

def runcommand(container, commands):
    print(OKGREEN+container.name+ENDC)
    # Start the container (if not started)
    started=False
    if not container.running:
        if not container.start():
            return
        started=True

    if not container.state == "RUNNING":
        return

    # Wait for connectivity
    if not container.get_ips(timeout=30):
        return

    # Run the command
    for command in commands:
        container.attach_wait(lxc.attach_run_command,command.split(' '))

    # Shutdown the container
    if started:
        if not container.shutdown(30):
            container.stop()

def main():
    commands = sys.argv[1:]
    for command in commands:
        print(command)
    input('Ready to run all these commands? ctrl-c to cancel')
    for container in lxc.list_containers(as_object=True):
        runcommand(container, commands)

if __name__=='__main__':
    main()

