#! /bin/bash

LXC_NAME=$1
DETACH=$2
CONTAINERS_PATH="/home/hack4u/.local/share/lxc"
VG_NAME="lxc"
MAPPER_PATH="/dev/mapper"
USER="hack4u"
USER_MAPPED_ID="231072"
GROUP=$USER

# Check if LV is mounted
if ! mount | grep $MAPPER_PATH/$VG_NAME-$LXC_NAME > /dev/null; then
	echo "Mouting LV"
	sudo mount $MAPPER_PATH/$VG_NAME-$LXC_NAME $CONTAINERS_PATH/$LXC_NAME
fi
# Retrieve owner and group of mounted point
owner=$(ls -ld $CONTAINERS_PATH/$LXC_NAME | awk '{ print $3 }')
group=$(ls -ld $CONTAINERS_PATH/$LXC_NAME | awk '{ print $4 }')
# Check if owner and group are ok
if [ "$owner:$group" != "$USER_MAPPED_ID:$GROUP" ]; then
	echo "Setting user:group"
	sudo chown $USER_MAPPED_ID:$GROUP $CONTAINERS_PATH/$LXC_NAME
fi

# Check permissions
if [ $(stat -c %A $CONTAINERS_PATH/$LXC_NAME) != "drwxrwx---" ]; then
	echo "Setting permissions"
	sudo chmod 770 $CONTAINERS_PATH/$LXC_NAME
fi

lxc-start -n $LXC_NAME $DETACH

exit 0